### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by christianholland** [dbdimitrov/BingleSeq#1]
Hi David,

some minor comments I forgot to mention yesterday:

* For the application it would be nice if you could provide some example data within the application (Could be similar to what I have done in the tab `Enrichment analysis` of this app: https://saezlab.shinyapps.io/reheat/). This would allow interested users and potential reviewers to explore your app in depth without the need to upload own data

* You mixed up the x and y labels of the volcano plot in the README file

* In my opinion It is a better practice to show the unadjusted p-value on the y-axis of the volcano plot. Why? Different p-values could map to the same adjusted p-value, so you loose some distinction/information between different genes. However, as a cutoff for regulation you should still use the corrected p-value

All the best,
Christian

**Comment by dbdimitrov** [comment]
Hi Christian,

I appreciate the comments and suggestions. 

The Volcano plot labels are now amended and I have changed the p-values in the VP according to your suggestion.

Also, example data does make a lot of sense for both potential users and reviewers. As such, example data has now been added for both Bulk and single-cell RNA-Seq.

I will mark this issue as closed, but please do not hesitate to open new ones in case you noticed anything else that could be improved.

Thanks a lot!

Kind regards,

Daniel
