### ISSUE TITLE
encountered data format error when running DE analysis after batch correction

### ISSUE THREAD

**Issue by UMKG** [dbdimitrov/BingleSeq#5]
Hi

I encountered an Data format error when running Differential Expression with batch correction, but didn't without the correction process. 
The error messages are described below:
```
警告:  'show_waiter' is deprecated.
Use 'waiter_show' instead.
See help("Deprecated") and help("waiter-deprecated").
 警告:  'hide_waiter' is deprecated.
Use 'waiter_hide' instead.
See help("Deprecated") and help("waiter-deprecated").
 警告:  Error in rownames_to_column: is.data.frame(df) is not TRUE
  113: <Anonymous>
```

Thank you.

**Comment by dbdimitrov** [comment]
Hi,

Could you please provide your session info and the header of the metadata table that you are using?

Best regards,
Daniel
