### ISSUE TITLE
How to start GUI

### ISSUE THREAD

**Issue by notgoodatR** [dbdimitrov/BingleSeq#6]
Hello,
Is it possible for you to add some steps describing how to actually launch the GUI?  I managed to get everything installed, but can't figure that out.

This is really attractive to someone like me who would like to play around in Seurat, etc. but never finds the time to actually learn R.

Thanks!

**Comment by MustafaElshani** [comment]
After installing
`BingleSeq::startBingleSeq()`

**Comment by dbdimitrov** [comment]
Hi,

I have now updated the readme to include the command. Thanks both!
