### ISSUE TITLE
metadata for 10x single cell data? 

### ISSUE THREAD

**Issue by nicinkjh** [dbdimitrov/BingleSeq#8]
I have two questions. 
1) Is it possible to load metadata for single cell RNAseq in BingleSeq? 

2) I have 10x count data of 49 cells which are fewer than 50. It creates issue when running unsupervised clustering, because default setting is 50 cells. But I cannot change in BingleSeq module. 

Warning: Error in irlba: max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Do you have suggestion?

Thanks,

**Comment by dbdimitrov** [comment]
Hi,

I can double check it try to have it solved by end of next week.

Thanks for opening an issue :)

**Comment by dbdimitrov** [comment]
Hi again,

You are right, I think the issue likely arises from the PCA dimensionality reduction which is by default set to 50 PCs.
However, I'm not sure if setting it to a lower value on my side would be the best solution either, as I prefer to keep the tool as generalize as possible, and I think the comparatively low dimensionality of your dataset is a bit specific.

One solution could be to fork the repo and change the following line on your side:
`scaled_object <- RunPCA(scaled_object, features = VariableFeatures(object = scaled_object))`
to e.g.
`scaled_object <- RunPCA(scaled_object, features = VariableFeatures(object = scaled_object), npcs=30)`


Also, at this stage, BingleSeq does not support external metadata for scRNA-Seq.

Thanks!
